### ISSUE TITLE
报错CPU不支持AVX指令

### ISSUE THREAD

**Issue by nine-city** [QPT-Family/QPT#52]
2022-04-13 17:48:42,477 INFO: 1|为保证可以成功在NoAVX平台执行PaddlePaddle，即将忽略小版本号进行安装PaddlePaddle-NoAVX

2022-04-13 17:48:42,477 INFO: 2|当前CPU不支持AVX指令集，正在尝试在线下载noavx版本的PaddlePaddle

2022-04-13 17:48:42,477 INFO: ----------ERROR SUMMARY
2022-04-13 17:48:42,478 INFO: 3|在执行终端命令时检测到了失败，完整信息如下：
(base) PS D:\desktop\project\python\pyseg\EISeg\out\Debug> cd D: ;D:\desktop\project\python\pyseg\EISeg\out\Debug\Python\python.exe -m pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir C:\Users\QY\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev7\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
Looking in links: https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle

但是我的CPU是12代i5 12400，是支持AVX的呀

![image](https://user-images.githubusercontent.com/20138490/163153267-235ee623-671d-4352-a000-2eda863495c3.png)

**Comment by GT-ZhangAcer** [comment]
当前信息无法定位问题，属于低效Issue，请务必按Issue模板重新提交谢谢！
