### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by LFeightyFour** [QPT-Family/QPT#54]
首次运行生成的DEBUG.exe时，提示我缺少bce库导致生成失败
于是我想通过CopyWhl2Packages方式将这个库手动加入安装
但是qpt.modules.package代码似乎已经改动过了，没有这个模块了，文档也没有更新
希望能提供一下导入方式，并更新一下文档

**Comment by GT-ZhangAcer** [comment]
当前信息无法定位问题，属于低效Issue，请务必按Issue模板重新提交谢谢！

**Comment by GT-ZhangAcer** [comment]
这并不是文档问题，最新版本框架就是这个导入方式，无关文档；而且最新版本并不会有bce这个问题，这也是为什么说需要按issue模板来提交issue！

**Comment by LFeightyFour** [comment]
谢谢，我刚刚也留意到了这个问题，发现github上最新的package代码中是有这个模块的，检查了一下，是我Anaconda环境中安装的QPT版本不是最新，你可以删除这个issue了，它似乎没有什么意义，谢谢回复
