### ISSUE TITLE
[Report]想确认一下qpt打包后是不是一定要包含程序的py文件

### ISSUE THREAD

**Issue by LFeightyFour** [QPT-Family/QPT#56]
**简要描述Bug**
想确认一下qpt打包后是不是一定要包含py文件，打包完成后发现resources文件夹下有程序的py文件，而一旦删除文件，exe就无法执行了，提示缺少该文件

**基本信息**
QPT版本：1.0b3.dev7

**Comment by GT-ZhangAcer** [comment]
可自行使用cython使其成为pyd格式，这样与Pyinstaller的散装模式是差不多一致的。如果要打包为单个文件可以考虑做成自解压压缩包+自动运行对应EXE+UPX加壳，这样和Pyinstaller的One file模式是差不多一致的。  
QPT在上半年有类似的计划，但排期靠后，最近工作略忙更新会相对慢一点（之前也不见得快）
