### ISSUE TITLE
读取requirement.txt依赖错误

### ISSUE THREAD

**Issue by LFeightyFour** [QPT-Family/QPT#61]
### QPT版本

1.0b3.dev7

### 操作系统版本

Windows 10

### CPU型号

Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz

### 核心信息填写

**复现步骤/报错截图**  
  2022-05-07 13:54:53,254 INFO: ----------ERROR SUMMARY
2022-05-07 13:54:53,254 INFO: 2|在执行终端命令时检测到了失败，完整信息如下：
PS C:\QPT_UT_OUT_CACHE\GPU_VERSION\Debug> cd C: ;C:\QPT_UT_OUT_CACHE\GPU_VERSION\Debug\Python\python.exe -m pip install -r C:/q_tmp\Cache\FileSerialize.tmp --target C:\QPT_UT_OUT_CACHE\GPU_VERSION\Debug\Python\Lib\site-packages --no-index -f C:\QPT_UT_OUT_CACHE\GPU_VERSION\Debug\opt/packages --isolated --disable-pip-version-check --cache-dir C:/q_tmp\pip_cache --timeout 10 --prefer-binary; echo "---QPT OUTPUT STATUS CODE---" ;$?
Looking in links: c:\QPT_UT_OUT_CACHE\GPU_VERSION\Debug\opt/packages
ERROR: Could not find a version that satisfies the requirement stor==0.8.1 (from versions: none)
ERROR: No matching distribution found for stor==0.8.1
## 步骤描述  
运行qpt2exe.py程序没有报错，生成了文件，但运行debug.exe文件时，报错如上，我没有使用auto模式，是直接使用了requirement.txt文件，其中应该是有个astor库，但报错提醒是找不到stor
  
## 【如报错则必须提供】Requirements文件内容 
  
```  
↓建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↓  
astor==0.8.1
Babel==2.10.1
bce-python-sdk==0.8.64
cachetools==5.0.0
certifi==2021.10.8
cfgv==3.3.1
charset-normalizer==2.0.12
click==8.1.2
colorama==0.4.4
cssselect==1.1.0
cssutils==2.4.0
cycler==0.11.0
Cython==0.29.28
decorator==5.1.1
distlib==0.3.4
et-xmlfile==1.1.0
filelock==3.6.0
flake8==4.0.1
Flask==2.1.1
Flask-Babel==2.0.0
fonttools==4.33.2
future==0.18.2
geojson==2.5.0
identify==2.4.12
idna==3.3
imageio==2.17.0
imgaug==0.4.0
importlib-metadata==4.11.3
itsdangerous==2.1.2
Jinja2==3.1.1
joblib==1.1.0
kiwisolver==1.4.2
lap==0.4.0
lmdb==1.3.0
lxml==4.8.0
MarkupSafe==2.1.1
matplotlib==3.5.1
mccabe==0.6.1
motmetrics==1.2.5
networkx==2.8
nodeenv==1.6.0
numpy==1.19.3
opencv-contrib-python==4.4.0.46
opencv-python==4.5.5.64
openpyxl==3.0.9
packaging==21.3
paddledet==2.4.0
paddleocr==2.4.0.4
paddlepaddle-gpu==2.2.2.post111
pandas==1.4.2
pefile==2021.9.3
Pillow==9.1.0
platformdirs==2.5.2
pre-commit==2.18.1
premailer==3.10.0
protobuf==3.20.1
pyclipper==1.3.0.post2
pycodestyle==2.8.0
pycryptodome==3.14.1
pyflakes==2.4.0
pyparsing==3.0.8
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.10.1
python-dateutil==2.8.2
python-Levenshtein==0.12.2
pytz==2022.1
PyWavelets==1.3.0
PyYAML==6.0
QPT==1.0b3.dev7
requests==2.27.1
scikit-image==0.19.2
scikit-learn==1.0.2
scipy==1.8.0
Shapely==1.8.1.post1
shellcheck-py==0.8.0.4
six==1.16.0
sklearn==0.0
terminaltables==3.1.10
threadpoolctl==3.1.0
tifffile==2022.4.22
toml==0.10.2
tqdm==4.64.0
ttkbootstrap==0.5.1
typeguard==2.13.3
urllib3==1.26.9
virtualenv==20.14.1
visualdl==2.2.3
Werkzeug==2.1.1
wget==3.2
wincertstore==0.2
xmltodict==0.12.0
zipp==3.8.0

...  
  
↑建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↑  
```  
  
## 【如报错则必须提供】完整打包日志   
```  
↓建议在此处粘贴完整日志↓  
  
↑建议在此处粘贴完整日志↑  
```  
  
## 完整运行日志（如打包时已报错，此处可选）  
  
```  
↓建议在此处粘贴完整日志↓  
  
↑建议在此处粘贴完整日志↑  
```

**Comment by GT-ZhangAcer** [comment]
试试
```
# xxx

astor==0.8.1
```
在最新的dev版本中好像有这个问题，下个版本会随重构直接修复

**Comment by GT-ZhangAcer** [comment]
已修复 https://github.com/QPT-Family/QPT/releases/tag/V1.0b3
