### ISSUE TITLE
1.0b4.dev1 Anaconda使用异常

### ISSUE THREAD

**Issue by BigerPatax** [QPT-Family/QPT#69]
## Issue类型
反馈
遍历wincertstore包的时候info_location为None，导致CreateExecutableModule打包中断
开发分支/qpt/kernel/qpackage.py—>139行
## 我的想法
```python
...
for package_dist in get_default_environment().iter_installed_distributions():
    name = package_dist.raw_name
    version = package_dist.version.public
    # 暂时跳过处理
    if package_dist.info_location is None:
        continue;
    top_file_path = os.path.join(package_dist.info_location, "top_level.txt")
...
```
## 期待的回应
有没有更好的处理方式

**Comment by GT-ZhangAcer** [comment]
不使用anaconda是这个版本最好的方式



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月18日(周六) 上午10:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [QPT-Family/QPT] 增加代码容错率/异常处理 (Issue #69)




 
Issue类型
 
反馈
 遍历wincertstore包的时候info_location为None，导致CreateExecutableModule打包中断
 开发分支/qpt/kernel/qpackage.py—&gt;139行
 
我的想法
 ... for package_dist in get_default_environment().iter_installed_distributions():     name = package_dist.raw_name     version = package_dist.version.public     # 暂时跳过处理     if package_dist.info_location is None:         continue;     top_file_path = os.path.join(package_dist.info_location, "top_level.txt") ...
 
期待的回应
 
有没有更好的处理方式

**Comment by GT-ZhangAcer** [comment]
新版本1.0b4.dev2已经尝试修复，如后续仍有问题可以继续在issue中更新情况~https://github.com/QPT-Family/QPT/releases/tag/V1.0b4_2
