### ISSUE TITLE
还有很长的路要走

### ISSUE THREAD

**Issue by Johnserf-Seed** [QPT-Family/QPT#7]
Debug与Release 这两个文件夹完全是多余且占空间的存在，我以为就是生成单个exe或者类似pyi -D的命令效果
**打包打包  我只需要你打包完成给我一个可执行文件，具备应有的依赖就可以了。**
项目所称的精简我用了一下，非常的不好用。而且内置库也仅有几个深度学习库

1. 控制台界面花里胡哨，给了非常多的输入性命令  但我只需要一条打包命令即可，哪里有出错直接控制台打印error即可
2.  打包的文件巨大（居然是复制文件?，项目中只能识别.gitignore文件排除添加文件，但是其他非代码文件全部复制)、不会自动识别upx等其他加壳工具、不能自定ico、命令功能少、不会生成打包步骤文件方便下次直接执行
3.  pyinstaller完全秒杀QPT，无论是速度、性能、大小。而且相同平台用QPT打包的exe模块缺一少两的
4.  追求**简单**摒弃**复杂**
5.  兼容平台只有win，没有mac os、linux
6.  生成的可执行文件无法签名，也不能添加详细信息（这一点就直接抛弃了）

**Comment by GT-ZhangAcer** [comment]
感谢对QPT的关注，但QPT现在从Release第一个版本到现在还不到两个月，团队并非全职维护，功能不可能一下子都会有的。  
最重要的是当前版本为EAP，仅做尝鲜使用，如果要以一个正式版本的态度来要求QPT，我个人认为太严格，甚至有些生气。  

关于“Debug与Release 这两个文件夹完全是多余且占空间的存在，我以为就是生成单个exe或者类似pyi -D的命令效果
打包打包 我只需要你打包完成给我一个可执行文件，具备应有的依赖就可以了。”，一般打包会有onefile和和QPT当前这样的散装模式，onfile虽然也在Todo列表当中，考虑到QPT更倾向深度学习程序，在没有更好的性能方案前所EAP版本的QPT并不会优先做。  
关于"控制台界面花里胡哨，给了非常多的输入性命令"，由于目前很多地方在设计上只是能用的范围，所以为了降低意外的故障暂时会加入很多需要确认的地方。  
关于"打包的文件巨大"，如果是拿QPT和onefile对比，这样不合适，onefile要压缩，散装的代码在发布时也要压缩，如果要对比也应当是和散装的形式做对比。目前我在测试其它打包工具，在打包PaddlePaddle这样的深度学习库中均为QPT胜出。  
关于"不能自定ico、命令功能少"同EAP  
关于“不会生成打包步骤文件方便下次直接执行”，这个是有的，无非是QPT放在了临时文件，相信在打包时候的最后一步也有给你提示，不能因为个人没有发现而说QPT没有，这样很不合适。  
关于“pyinstaller完全秒杀QPT，无论是速度、性能、大小。而且相同平台用QPT打包的exe模块缺一少两的”同EAP。另外Pyinstaller的Contributor为100+，项目自创建至当前的时间是QPT的百倍，我不认为个人非全职开发者可以在2月内追平对方，如果你可以当然也可以证明给我看。  
关于“兼容平台只有win，没有mac os、linux”同EAP。  
关于“生成的可执行文件无法签名，也不能添加详细信息（这一点就直接抛弃了）”同EAP，后续会给出SFX相关内容。  

以上大部分内容均在QPT的ToDo列表中，如果有认真在看QPT，我相信大部分答案已经有所体现，issue虽然很好，但意义不大，因为你看到的我也有看到。  

另外，QPT所解决的问题和Pyinstaller不一样，对于部分国产深度学习开源框架的开发者，他们使用Pyinstaller并不能很好解决CUDA、NoAVX等问题，这些是QPT可以解决的。  
如果做一个一模一样的东西只是技术方案有所变化，Me too me later，而且十有八九一辈子也追不上，也不是QPT想要完成的事情，也不是2个月就能完成的事情。

你说的很对，QPT确实还有很长的路要走，这个项目我也会长期维护，相信时间会给出个及格的答卷。
