### ISSUE TITLE
[Bug] Win7下打开可执行程序无效应

### ISSUE THREAD

**Issue by haiw2sm** [QPT-Family/QPT#78]
### QPT版本

1.0b4.dev6

### 操作系统版本

Windows 7

### CPU型号

i5-6700

### 核心信息填写

**复现步骤/报错截图**  
  
## 步骤描述  
1. 仓库官方README.md
  
## 【如报错则必须提供】Requirements文件内容 
  
```  
无报错，window10下调试测试完毕成功后解压移植到的win7 旗舰版  
```  
 
## 【如报错则必须提供】完整打包日志   
```  
1. 现象：打开Realease压缩包后安装运行可执行程序，无兼容弹窗与任何可视化响应
2. 自检：
2.1 检测logs文件 发现程序打印的日志始终停留再 PIPTerminal
2.2 检测后台任务管理器 `Python/python.exe` 保持运行

```  
  
## 完整运行日志（如打包时已报错，此处可选）  
  
```  

```

**Comment by GT-ZhangAcer** [comment]
QPT目前不对Windows7进行维护，维护成本过高，谢谢
