### ISSUE TITLE
建议：能打包pyd吗？这个项目所有代码都是裸露的，想简单加密下

### ISSUE THREAD

**Issue by ahaaaaaaaa** [QPT-Family/QPT#79]
## Issue类型
建议

## 我的想法
打包pyd也是算加密了（x

**Comment by GT-ZhangAcer** [comment]
主程序不是pyd即可，可以新建py文件作为主程序，然后import对应pyd文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月4日(周二) 晚上7:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [QPT-Family/QPT] 建议：能打包pyd吗？这个项目所有代码都是裸露的，想简单加密下 (Issue #79)




 
Issue类型
 
建议
 
我的想法
 
打包pyd也是算加密了（x
 
期待的回应
