### ISSUE TITLE
[Report]→打包好的程序文件无法运行←

### ISSUE THREAD

**Issue by NoMorePlay111** [QPT-Family/QPT#82]
### QPT版本

1.0b4.dev6

### 操作系统版本

Windows 7

### CPU型号

i7 6700

## 步骤描述  
在本地windows10， i7-10870H，anaconda建立的python3.8 环境下编写了个小程序
调用paddleocr（cpu版本）识别图片，读取数据填入excel中
pycharm运行测试没问题，打包没问题，打包后本地测试没问题（需要手动调节一些库的文件，已经解决）

将打包好的程序导入一台不联网的电脑中，win7，i7 6700，无法运行，会报错

![微信图片_20230311001651](https://user-images.githubusercontent.com/123803710/224367899-5fbc6e55-c0aa-4267-8824-a8462a396ce8.jpg)

## Requirements文件内容 
keyboard==0.13.5
paddleocr==2.6.1.3
visualdl==2.5.0
paddlepaddle==2.4.2

**Comment by guoliangxie123** [comment]
打包完后出现了这个问题
  File "E:\code\python\dabao\Releasecopy\Python\Lib\site-packages\qpt\memory.py", line 83, in get_win32api
    import win32api
ImportError: DLL load failed: 找不到指定的模块。

**Comment by GT-ZhangAcer** [comment]
QPT不会考虑win7系统，盗版占用率较高部分Python组件适配较差，故不考虑
