### ISSUE TITLE
[Report]→请在此处填写Issue标题←ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by mahnazislam1010** [QPT-Family/QPT#85]
### QPT版本

1.0b4.dev6

### 操作系统版本

Windows 10

### CPU型号

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz RAM: 64GB

### 核心信息填写

**复现步骤/报错截图**  
  
## 步骤描述  
（可描述您参考了哪些文档中的步骤，或自己在做哪些操作时遇到了问题，社区维护者可以通过该描述来尽可能复现您的情况）
  
## 【如报错则必须提供】Requirements文件内容 
  
```  
↓建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↓  
  
Example:  
  
paddlepaddle==2.2.2  
opencv-python>=4.1  
...  
  
↑建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↑  
```  
  
## 【如报错则必须提供】完整打包日志   
```  
↓建议在此处粘贴完整日志↓  
  
↑建议在此处粘贴完整日志↑  
```  
  
## 完整运行日志（如打包时已报错，此处可选）  
  
```  
↓建议在此处粘贴完整日志↓  
  
↑建议在此处粘贴完整日志↑  
```  
  
## 其他信息
 File "C:\Users\AV\PycharmProjects\pythonProject5\out\Release\Python\Lib\site-packages\paddleocr\paddleocr.py", line 25, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by GT-ZhangAcer** [comment]
当前版本下，建议避开类似'user'这样的目录，因为这个目录是中文的，opencv这样的库对中文支持不友好
