### ISSUE TITLE
module 'mil' has no attribute 'MIL_ID'

### ISSUE THREAD

**Issue by zack-rgb** [QPT-Family/QPT#86]
### QPT版本

1.0b4.dev6

### 操作系统版本

Windows 10

### CPU型号

intel(R) core(TM) i9-10900X cpu @3.70GHz

### 核心信息填写

**复现步骤/报错截图**  
  
## 步骤描述  
（可描述您参考了哪些文档中的步骤，或自己在做哪些操作时遇到了问题，社区维护者可以通过该描述来尽可能复现您的情况）
  
## 【如报错则必须提供】Requirements文件内容 
  
```  
↓建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↓  
  
Example:  
  
thop==0.0.31.post2005241907
torch==1.10.2
typing_extensions==4.1.1
torchvision==0.11.3
numpy==1.22.3
pillow==9.0.1
pyzbar==0.1.9
mil==1.0.5
pywin32==225
onnxruntime_gpu==1.11.0
protobuf==3.19.4
flatbuffers==2.0
seaborn==0.11.0
matplotlib==3.5.1
pyparsing==3.0.7
cycler==0.11.0
packaging==21.3
fonttools==4.30.0
kiwisolver==1.4.0
python_dateutil==2.8.2
six==1.16.0
pandas==1.1.4
pytz==2021.3
scipy==1.8.0
pyyaml==6.0
pyserial==3.5
opencv_python==4.5.5.64
# Ignore future==0.18.2
tqdm==4.63.0
colorama==0.4.4
uff==0.6.9
tensorboard==2.8.0
tensorboard_data_server==0.6.1
werkzeug==2.0.3
requests==2.27.1
certifi==2022.5.18.1
charset_normalizer==2.0.12
idna==3.3
urllib3==1.26.9
google_auth_oauthlib==0.4.6
google_auth==2.6.2
rsa==4.8
pyasn1==0.4.8
pyasn1_modules==0.2.8
cachetools==5.0.0
requests_oauthlib==1.3.1
oauthlib==3.2.0
absl_py==1.0.0
markdown==3.3.6
importlib_metadata==4.11.3
zipp==3.7.0
grpcio==1.44.0
wheel==0.38.4
setuptools==66.0.0
tensorboard_plugin_wit==1.8.1
qscintilla==2.13.2
pyqt5==5.15.6
pyqt5_qt5==5.15.2
pyqt5_sip==12.9.1
onnx_graphsurgeon==0.3.12
onnx==1.11.0

...  
  
↑建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↑  
```  
  
## 【如报错则必须提供】完整打包日志   
```  
↓建议在此处粘贴完整日志↓  
  
↑建议在此处粘贴完整日志↑  
```  
  
## 完整运行日志（如打包时已报错，此处可选）  

 在打包完成后，运行出现这个报错的
 module 'mil' has no attribute 'MIL_ID'

**Comment by zack-rgb** [comment]
我打包没有报错，就是在运行的时候报错了

**Comment by GT-ZhangAcer** [comment]
请提供打包后首次运行的完整日志，谢谢



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 24, 2023 09:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: [QPT-Family/QPT] module 'mil' has no attribute 'MIL_ID' (Issue #86)




 
QPT版本
 
1.0b4.dev6
 
操作系统版本
 
Windows 10
 
CPU型号
 
intel(R) core(TM) i9-10900X cpu @3.70GHz
 
核心信息填写
 
复现步骤/报错截图
 
步骤描述
 
（可描述您参考了哪些文档中的步骤，或自己在做哪些操作时遇到了问题，社区维护者可以通过该描述来尽可能复现您的情况）
 
【如报错则必须提供】Requirements文件内容
 ↓建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↓      Example:      thop==0.0.31.post2005241907 torch==1.10.2 typing_extensions==4.1.1 torchvision==0.11.3 numpy==1.22.3 pillow==9.0.1 pyzbar==0.1.9 mil==1.0.5 pywin32==225 onnxruntime_gpu==1.11.0 protobuf==3.19.4 flatbuffers==2.0 seaborn==0.11.0 matplotlib==3.5.1 pyparsing==3.0.7 cycler==0.11.0 packaging==21.3 fonttools==4.30.0 kiwisolver==1.4.0 python_dateutil==2.8.2 six==1.16.0 pandas==1.1.4 pytz==2021.3 scipy==1.8.0 pyyaml==6.0 pyserial==3.5 opencv_python==4.5.5.64 # Ignore future==0.18.2 tqdm==4.63.0 colorama==0.4.4 uff==0.6.9 tensorboard==2.8.0 tensorboard_data_server==0.6.1 werkzeug==2.0.3 requests==2.27.1 certifi==2022.5.18.1 charset_normalizer==2.0.12 idna==3.3 urllib3==1.26.9 google_auth_oauthlib==0.4.6 google_auth==2.6.2 rsa==4.8 pyasn1==0.4.8 pyasn1_modules==0.2.8 cachetools==5.0.0 requests_oauthlib==1.3.1 oauthlib==3.2.0 absl_py==1.0.0 markdown==3.3.6 importlib_metadata==4.11.3 zipp==3.7.0 grpcio==1.44.0 wheel==0.38.4 setuptools==66.0.0 tensorboard_plugin_wit==1.8.1 qscintilla==2.13.2 pyqt5==5.15.6 pyqt5_qt5==5.15.2 pyqt5_sip==12.9.1 onnx_graphsurgeon==0.3.12 onnx==1.11.0 ...      ↑建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↑    
【如报错则必须提供】完整打包日志
 ↓建议在此处粘贴完整日志↓      ↑建议在此处粘贴完整日志↑    
完整运行日志（如打包时已报错，此处可选）
 
在打包完成后，运行出现这个报错的
 module 'mil' has no attribute 'MIL_ID'

**Comment by zack-rgb** [comment]
→[2023-04-24 09:29:56,810] [DEBUG] | Active code page: 65001
→[2023-04-24 09:29:56,814] [DEBUG] | 终端命令执行成功！
→[2023-04-24 09:29:56,814] [DEBUG] | 正在连接PIPTerminal
→[2023-04-24 09:29:56,833] [DEBUG] | 已设置PIP跨版本编译模式，目标解释器路径为：D:\app\Release\Python\python.exe
→[2023-04-24 09:29:56,839] [DEBUG] | SHELL: chcp 65001
→[2023-04-24 09:29:56,906] [DEBUG] | Windows PowerShell
→[2023-04-24 09:29:56,906] [DEBUG] | Copyright (C) Microsoft Corporation. All rights reserved.
→[2023-04-24 09:29:56,907] [DEBUG] | Try the new cross-platform PowerShell https://aka.ms/pscore6
→[2023-04-24 09:29:57,112] [DEBUG] | PS D:\app\Release> chcp 65001 ; echo "---QPT OUTPUT STATUS CODE---" $?
→[2023-04-24 09:29:57,123] [DEBUG] | Active code page: 65001
→[2023-04-24 09:29:57,126] [DEBUG] | 终端命令执行成功！
→[2023-04-24 09:29:57,126] [DEBUG] | 正在连接PTerminal
→[2023-04-24 09:29:59,071] [INFO] | 初次使用将会适应本地环境，可能需要几分钟时间，请耐心等待...
初始化进度-24 091/5  |━━━━                | 20.00% AutoPythonEnv部署中...→[2023-04-24 09:29:59,078] [DEBUG] | 正在加载AutoPythonEnv-UnPackPythonEnvOptOP
初始化进度-24 092/5  |━━━━━━━━            | 40.00% QPTDependencyPackage部署中...→[2023-04-24 09:29:59,081] [DEBUG] | 正在加载QPTDependencyPackage-LocalInstallWhlOptOP
→[2023-04-24 09:29:59,081] [DEBUG] | 找到该OP状态文件LocalInstallWhlOpt.inactive，故跳过该OP
初始化进度-24 093/5  |━━━━━━━━━━━━        | 60.00% AutoRequirementsPackage部署中...→[2023-04-24 09:29:59,083] [DEBUG] | 正在加载AutoRequirementsPackage-LocalInstallWhlOptOP
→[2023-04-24 09:29:59,083] [DEBUG] | 找到该OP状态文件LocalInstallWhlOpt.inactive，故跳过该OP
初始化进度-24 094/5  |━━━━━━━━━━━━━━━━    | 80.00% 初始化完毕→[2023-04-24 09:29:59,108] [INFO] | ----------WARNING SUMMARY
→[2023-04-24 09:29:59,109] [INFO] | 0|C:\Users\ADMINI~1\AppData\Local\Temp\QPT_Cache_V/1.0b4.dev6中 ~ 字符会可能影响使 用。


→[2023-04-24 09:29:59,109] [INFO] | 1|当前系统的用户名中包含中文/空格等可能会对程序造成异常的字符，现已默认QPT临时目录 为C:/q_tmp


→[2023-04-24 09:29:59,109] [INFO] | ----------ERROR SUMMARY
→[2023-04-24 09:29:59,111] [INFO] | ----------生成状态WARNING:2 ERROR:0
→[2023-04-24 09:29:59,111] [DEBUG] | SHELL: cd "D:\app\Release\resources";./../Python/python.exe "D:\app\Release\resources\winV2.py"
PS D:\app\Release> cd "D:\app\Release\resources";./../Python/python.exe "D:\app\Release\resources\winV2.py"  ; echo "---QPT OUTPUT STATUS CODE---" $?
0.25 0.45 1000 0.1 .jpg True D:\DefectDetect\DefectImg\ *** 2023-04-24 0 0 0 白色 白色_2.8mm 2.8 10
29.336111886160715
socket
Traceback (most recent call last):
  File "D:\app\Release\resources\detectProV10.py", line 27, in <module>
    class HookDataStruct(ctypes.Structure):
  File "D:\app\Release\resources\detectProV10.py", line 29, in HookDataStruct
    ("MilDigitizer", mil.MIL_ID),
AttributeError: module 'mil' has no attribute 'MIL_ID'

**Comment by GT-ZhangAcer** [comment]
请提供打包后首次运行的完整日志，注意是打包后首次运行的日志，谢谢
