### ISSUE TITLE
已安装模块 运行时报错

### ISSUE THREAD

**Issue by nfh994** [QPT-Family/QPT#90]
### QPT版本

1.0b4.dev6

### 操作系统版本

Windows 11

### CPU型号

e5 2680 v2

### 核心信息填写

**复现步骤/报错截图**  
  
## 步骤描述  
正常打包后 运行debug，报错
import win32api
ImportError: DLL load failed: 找不到指定的模块。
  
## 【如报错则必须提供】Requirements文件内容 
  
↓建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↓  
  
[requirements.txt](https://github.com/QPT-Family/QPT/files/11392862/requirements.txt)

  
↑建议在此处粘贴完整Requirements（Python第三方依赖）列表信息↑  
  
## 【如报错则必须提供】完整打包日志   

[打包日志.txt](https://github.com/QPT-Family/QPT/files/11392866/default.txt)

  
## 完整运行日志（如打包时已报错，此处可选）  
  
[dbug.txt](https://github.com/QPT-Family/QPT/files/11392871/dbug.txt)

## 其他信息
超出字数限制了，所以放文件

**Comment by GT-ZhangAcer** [comment]
从dbug.txt文件中可以看到，paddlepaddle这个包在安装时出现了问题，初步推测是CPU不支持NoAVX导致。若该CPU在开发环境可以正常运行paddle，则可以参考https://github.com/QPT-Family/QPT/blob/%E5%BC%80%E5%8F%91%E5%88%86%E6%94%AF/examples/advanced/%E4%BD%BF%E7%94%A8SubModule%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89whl.md 方式对paddle进行自定义安装，并删去requirement里的paddlepaddle
