### ISSUE TITLE
我想这可不可以将我们自己的源码进行一个加密处理[TWB]

### ISSUE THREAD

**Issue by zack-rgb** [QPT-Family/QPT#92]
## Issue类型
建议/意见/反馈 or 代码贡献请求

## 我的想法
我的想法是在别人用我们的这个软件的时候，他们看不到，或者他们看不出来是python的代码进行一个加密处理，这样的话，就可以保证自己的源码不泄露

**Comment by GT-ZhangAcer** [comment]
之前有计划在做，但现在工作忒忙了，周末没太多空闲时间更了。比较建议的是，可以直接转为pyd，pyinstaller那边也是这样做的，pyd可以比较轻松的包含大部分源代码
