### ISSUE TITLE
V1.0b5 在哪里找，是开发分支吗

### ISSUE THREAD

**Issue by MrRabbit2MissCat** [QPT-Family/QPT#97]
### QPT版本

V1.0b5

### 操作系统版本

Windows 10

### 核心信息填写

新版本

**Comment by GT-ZhangAcer** [comment]
抱歉，这两周去上海出差了，暂未同步至镜像源，待回家后进行上传

**Comment by MrRabbit2MissCat** [comment]
好的

**Comment by GT-ZhangAcer** [comment]
最新版本1.0b7已经适配，预计11.28日前同步各大pip镜像源，感谢支持。
