### ISSUE TITLE
python setup.py install 报错

### ISSUE THREAD

**Issue by MrRabbit2MissCat** [QPT-Family/QPT#98]
### QPT版本

1.0b4.dev7

### 操作系统版本

Windows 10

### 核心信息填写

**复现步骤/报错截图**  
![image](https://github.com/QPT-Family/QPT/assets/38371806/5b0bdc74-537e-42b6-9f93-0759f0f75430)
  
问题在setup.py

![image](https://github.com/QPT-Family/QPT/assets/38371806/cdec9772-e93e-4694-9bbb-15cbaab84825)

**Comment by GT-ZhangAcer** [comment]
请勿使用非GitHub、Gitee提供的代码，非官方的镜像源存在较高延时，会包含未修正的代码。同时不建议clone源码进行安装，可等待国内pypi镜像源同步后，使用同步后的whl包进行安装。

**Comment by MrRabbit2MissCat** [comment]
好的，我卸载了，使用pypi发布的安装了，报sdk错误
![image](https://github.com/QPT-Family/QPT/assets/38371806/d3693852-968b-41e7-a451-a99e61482c98)
